apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-identity-center
spec:
  package: ghcr.io/hops-ops/aws-identity-center:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}

---

apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-aws-identity-centerrender
spec:
  package: ghcr.io/hops-ops/aws-identity-center_render:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}
